/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CustomDatabase;

import CustomDatabase.core.QueryExpression;
import CustomDatabase.core.QueryPlan;
import CustomDatabase.core.QueryResultSet;
import CustomDatabase.queryexecutor.QueryExecutor;

import static CustomDatabase.core.Node.*;

public class App {

    public static void main(String[] args) {
        QueryPlan queryPlan = new QueryPlan(
                new QueryExpression(PROJECTION, "title"),
                new QueryExpression(SELECTION, "movieId", "EQUALS", "5000"),
                new QueryExpression(SCAN, "movies"));

        QueryExecutor queryExecutor = new QueryExecutor(queryPlan);
        QueryResultSet resultSet = queryExecutor.execute();
        System.out.println(resultSet);
    }
}
